import { Project } from '@prisma/client'
import { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import About from '../components/About'
import Hero from '../components/Hero'
import ProjectList from '../components/ProjectList'
import { prisma } from '../lib/prisma'

type Props = {
  projects: Project[]
}

const Home: NextPage<Props> = ({ projects }) => {
  return (
    <>
      <Head>
        <title>Kévin Colonjard | Développeur Frontend à Lyon</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Hero />

      <ProjectList projects={projects} />

      <About />
    </>
  )
}

export const getStaticProps: GetStaticProps = async () => {
  const projects = await prisma.project.findMany({
    where: {
      published: {
        equals: true
      }
    },
    orderBy: {
      createdAt: 'desc'
    },
    select: {
      id: true,
      slug: true,
      title: true,
      subtitle: true,
      color: true,
      thumbnail: true
    }
  })

  return {
    props: {
      projects: projects
    }
  }
}

export default Home
