import { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Kévin Colonjard | Développeur Frontend à Lyon</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <h1 className="text-3xl font-bold underline">Hello World</h1>
    </div>
  )
}

export default Home
